### PR TITLE
Change '/' to path.sep.

### PR DESCRIPTION
**Pull request by be5invis**
Potential fix of #92.

### CODE REVIEW

**Comment by zjhmale** [comment]
@be5invis After playing around our extension on windows7 and windows10, I finally figure out the reason under the hood, it is nothing related to the path separator, one wired thing of VSCode RTS on windows is that, e.g.

```javascript
let [dpath, module] = uri.split(innerCompilerOptions.src)
// module now is "\\TermLang\\Unify.idr"
let moduleParts = module.split(path.sep)
// moduleParts is ["\\TermLang\\Unify.idr"] which should be ["\\", "TermLang", "Unify.idr"] as expected
```

which is really confusing, but we can do the `split(path.sep)` in a normal nodejs prompt on windows.

Anyway, I got a final solusion to fix this without any annoying path splitting and joining.

**Comment by be5invis** [comment]
@zjhmale this fixes the issue on mu machine that `:l` ends up with empty string.

**Comment by be5invis** [comment]
@zjhmale what's the result of `path.sep`.

**Comment by zjhmale** [comment]
@be5invis the result of `path.sep` is "\\"

**Comment by zjhmale** [comment]
And #65 is causing when user start an REPL with single Idris file instead of an ipkg project.

**Comment by zjhmale** [comment]
Thanks!

**Pull request merged**
