### PR TITLE
Tweak text

### PR DESCRIPTION
**Pull request by philipcraig**
Make the text wording of the commands more natural

### CODE REVIEW

**Comment by zjhmale** [comment]
Thanks for this PR, but I believe the text in other places also need some polishment, e.g., https://github.com/zjhmale/vscode-idris/blob/master/CHANGELOG.md, https://github.com/zjhmale/vscode-idris/blob/master/FEATURES.md, https://github.com/zjhmale/vscode-idris/blob/master/README.md, can you also tweak them in this PR, thanks!

**Comment by philipcraig** [comment]
Hi, I will do the text. I don't know how to recapture the animations though. Are you able to do that yourself?

**Comment by zjhmale** [comment]
@philipcraig Sure, just leave the animations at the moment, I will recapture all of them when we set up a website for this extension #78 :)

**Comment by philipcraig** [comment]
I didn't do the changelog. It's because changelogs should be a record of what actually happened, so I didn't want to go back and change the changelog itself.

**Comment by zjhmale** [comment]
@philipcraig Thanks for all the work, this looks good to me and I will tweak the text on Changelog by myself :)

**Pull request merged**
