### PR TITLE
Fix incorrect dedentation & add record/mutual to keywords

### PR DESCRIPTION
**Pull request by be5invis**

### CODE REVIEW

**Comment by zjhmale** [comment]
Thanks @be5invis! But I have no idea why the CI is not triggered 😅

**Comment by be5invis** [comment]
@zjhmale So, are there any plan to publish a newer version?

**Comment by zjhmale** [comment]
@be5invis There is a plan, maybe after the syntax file migration? what do you think?

**Comment by be5invis** [comment]
@zjhmale I think maybe you can publish a `0.3.1` now with fixes, and a `0.4.0` after your migration is completed.

**Comment by zjhmale** [comment]
@be5invis OK, fair enough 😄 BTW, https://github.com/zjhmale/vscode-idris/issues/10 and https://github.com/zjhmale/vscode-idris/issues/13 are all related to the syntax issue right?

**Comment by be5invis** [comment]
@zjhmale Yes, and the current syntax should followed up Idirs 0.99.1's.

**Comment by zjhmale** [comment]
@be5invis Oh, btw, please accept my request on Wechat 😄

**Comment by zjhmale** [comment]
Cool
>@zjhmale Yes, and the current syntax should followed up Idirs 0.99.1's.

**Comment by be5invis** [comment]
@zjhmale Done.
ps. You should REALLY join the group that @marisakirisame established

image

**Pull request merged**
